Added kube-bash

diff --git a/bin/executable_http-load b/bin/executable_http-load
--- a/bin/executable_http-load
+++ b/bin/executable_http-load
@@ -1,6 +1,12 @@
 #!/bin/bash
-
 # Download a whole website
+
+# flag
+# e - Exit if any error
+# u - Treat unset variables as an error when substituting
+# o pipefail - the return value of a pipeline is the status of the last command to exit with a non-zero status or zero if no command exited with a non-zero status
+# E - the ERR trap is inherited by shell functions
+set -Eeuo pipefail
 
 # Check if URL is provided
 if [ -z "$1" ]; then
@@ -10,6 +16,10 @@ fi
 
 # Define the website URL
 WEBSITE_URL=$1
+
+LOAD_DIR=/tmp/http-load
+mkdir -p $LOAD_DIR
+pushd $LOAD_DIR || exit
 
 # Download the website and log details
 wget \
@@ -32,9 +42,11 @@ wget \
 # show-progress - display the progress bar in any verbosity mode
 # progress=type - select the progress bar type
 # timeout   - set all timeout values to SECONDS
+# no-parent - ensures it does not traverse to parent directories
 # waitretry - wait SECONDS between retries of a retrieval
 # output-document - will save the document (ie body response)
 
+popd
 
 # Count the number of requests made (lines starting with "HTTP" in the log)
 TOTAL_REQUESTS=$(grep -c "HTTP/" wget-log.txt)
diff --git a/bin/executable_kube-pods-ip b/bin/executable_kube-pods-ip
--- a/bin/executable_kube-pods-ip
+++ b/bin/executable_kube-pods-ip
@@ -1,6 +1,13 @@
 #!/bin/bash
 # Shows the pods ip (node name can be given for a smaller subset)
 
+# flag
+# e - Exit if any error
+# u - Treat unset variables as an error when substituting
+# o pipefail - the return value of a pipeline is the status of the last command to exit with a non-zero status or zero if no command exited with a non-zero status
+# E - the ERR trap is inherited by shell functions
+set -Eeuo pipefail
+
 # Check if the node name is provided
 if [ -n "$1" ]; then
   NAMESPACE_JSONPATH="{range .items[?(@.spec.nodeName==\"$1\")]}{.status.podIP}{\" \"}{.metadata.name}{\"\n\"}{end}"
