fix: claude error

diff --git a/bin-local/executable_claude-api-key-helper b/bin-local/executable_claude-api-key-helper
--- a/bin-local/executable_claude-api-key-helper
+++ b/bin-local/executable_claude-api-key-helper
@@ -17,11 +17,11 @@ fi
 # Key
 PROVIDER="anthropic"
 LLM_KEY_PATH="${PROVIDER}/${ORGANIZATION_NAME}/${PROJECT_NAME}"
-if ! LLM_KEY=$(pass "$LLM_KEY_PATH"); then
-  echo "${LLM:-} Api Key Not Found at $LLM_KEY_PATH" >&2
+if ! LLM_KEY=$(pass "$LLM_KEY_PATH" 2>/dev/null); then
+  echo "${LLM:-} Api Key Not Found at $LLM_KEY_PATH or pass error" >&2
   LLM_KEY_PATH="${PROVIDER}/${ORGANIZATION_NAME}/default"
-  if ! LLM_KEY=$(pass "$LLM_KEY_PATH"); then
-    echo "${LLM:-} Api Key Not Found at $LLM_KEY_PATH" >&2 >&2
+  if ! LLM_KEY=$(pass "$LLM_KEY_PATH" 2>/dev/null); then
+    echo "${LLM:-} Api Key Not Found at $LLM_KEY_PATH or pass error" >&2 >&2
     exit 1
   fi
 fi
